[package]
name = "compose_db"
version = "0.1.0"
authors = ["ferris"]

[dependencies]
lmdb-rs = "0.5.0"
iron = "*"
router = "*"
rustc-serialize = "*"


[[bin]]
name = "composedb_bare"
path = "src/bare_build.rs"


[[bin]]
name = "composedb_simple"
path = "src/simple_build.rs"
