[package]
name = "compose_db"
version = "0.1.0"
authors = ["ferris"]

[dependencies]
lmdb-rs = "0.5.0"
iron = "*"
router = "*"
rustc-serialize = "*"


[[bin]]
name = "combosedb_server"
path = "src/server.rs"
